/**
 * Default country settings
 * 
 * NOTE: These are fallback values only. Actual values should come from country-settings DB.
 * Use getDefaultCountry() from @/lib/data/country-settings to get current values.
 * These defaults are kept for backward compatibility and error handling.
 */
export const DEFAULT_COUNTRY = {
  countryCode: 'IN',
  countryName: 'India',
  phoneCountryCode: '+91',
  phonePattern: '^[0-9]{10}$',
  phoneLength: 10,
  pincodePattern: '^[0-9]{6}$',
  pincodeLength: 6,
  pincodeLabel: 'Pincode',
  states: [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Jammu and Kashmir',
    'Ladakh',
    'Lakshadweep',
    'Puducherry',
  ],
  currency: 'INR',
  currencySymbol: '₹',
  isActive: true,
  isDefault: true,
  order: 0,
} as const;
